backend:
  name: github
  repo: michelle-helpt-makers/website

media_folder: static/assets
public_folder: /assets

collections:
  - label: Pages
    format: markdown
    name: pages
    files:
      - label: Home
        name: home
        file: src/content/about.yml
        fields:
          - label: Tagline
            name: tagline
            widget: markdown
